config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'players#new'

  mount ActionCable.server => '/cable'

  # Skip registrations for now so no new users can sign up.
  devise_for :users, skip: [:registrations]

  # Allow users to sign up and automatically populate categories and post types
  # devise_for :users, controllers: { registrations: 'registrations' }

  post 'play', to: 'games#players_ready', as: 'players_ready'
  get 'play', to: 'players#new', as: 'join_game'
  get 'play/:game_code', to: 'players#new_with_code', as: 'join_game_with_code'

  resources :players, only: [:new, :create]
  resources :games, only: [:index, :new, :create, :show, :update] do
    get 'in_progress', to: 'games#game_in_progress', as: 'in_progress'
    resources :players, only: [:index]
    resources :rounds, only: [:show] do
      resources :submissions, only: [:new, :create]
    end
  end

  resources :decks, only: [:index, :new, :create, :edit, :update] do
    resources :questions, only: [:index, :new, :create, :edit, :update]
  end
  resources :questions, only: [:create]
  get '/convert_from_suggestion', to: 'questions#convert_from_suggestion'
  resources :suggested_questions, only: [:new, :create, :index, :show]
end

app/models/question.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: questions
#
#  id           :bigint           not null, primary key
#  adult_rating :boolean
#  archived     :boolean          default(FALSE)
#  text         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  deck_id      :bigint
#
# Indexes
#
#  index_questions_on_deck_id  (deck_id)
#
# Foreign Keys
#
#  fk_rails_...  (deck_id => decks.id)
#
class Question < ApplicationRecord
  belongs_to :deck
  has_many :rounds, dependent: :nullify
  validates :text, presence: true

  def self.active
    where(archived: false)
  end

  def self.search(field:, terms:)
    if terms.blank?
      active
    else
      where("#{field} ILIKE ?", "%#{terms}%")
    end
  end

  def self.without_adult_content
    active.where.not(adult_rating: true)
  end

  def active?
    archived == false
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create edit update]
  before_action :set_question, only: %i[edit update]
  before_action :set_deck, only: %i[index new create edit update]

  def index
    search_term = params[:search]
    @questions = @deck.questions.search(field: 'text', terms: search_term)
                      .order(:id)
                      .paginate(page: params[:page], per_page: 30)
  end

  def new
    @question = @deck.questions.new
  end

  def edit
    authorize(@question)
  end

  def create
    @question = @deck.questions.new(question_params)
    authorize(@question)

    if @question.save
      SuggestedQuestion.mark_as_processed(params[:suggested_question_id])
      redirect_to deck_questions_url(@deck)
    else
      render :new
    end
  end

  def update
    authorize(@question)

    if @question.update(question_params)
      redirect_to deck_questions_url(@deck)
    else
      render :edit
    end
  end

  def convert_from_suggestion
    @suggested_question = SuggestedQuestion.find(params[:suggested_question_id])
    @question = Question.new(text: @suggested_question.text)
    authorize(@question)

    render :new_from_suggestion
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_deck
    deck_id = params[:deck_id] || params[:question][:deck_id]
    @deck = Deck.find(deck_id)
  end

  def question_params
    params.require(:question)
          .permit(:user_id, :text, :adult_rating, :archived, :deck_id)
  end
end

app/views/questions/_form.html.erb
<section class='section'>
  <%= form_with(model: [deck, question], local: true) do |form| %>
  <%= render 'shared/errors', object: question %>
  <div class='columns'>
    <div class='field column is-three-quarters'>
      <div class='control'>
        <%= form.label 'Question' %>
        <%= form.text_field :text, class: 'input' %>
      </div>
    </div>

    <div class='field column'>
      <div class='control'>
        <label class='checkbox'>
          <%= form.check_box :adult_rating, class: 'checkbox' %>
          Adult Rating
        </label>
      </div>
    </div>

    <div class='field column'>
      <div class='control'>
        <label class='checkbox'>
          <%= form.check_box :archived, class: 'checkbox' %>
          Archived
        </label>
      </div>
    </div>
  </div><!-- columns -->

  <div class='mt-5 mb-5'>
    <%= form.submit class: button_classes %>
  </div>
  <% end %>
</section>

app/views/questions/edit.html.erb
<% content_for(:title, "Editing #{@question.text}") %>

<section class='section'>
  <header class='level'>
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><%= link_to 'Decks', decks_path %></li>
        <li><%= link_to "#{@deck.name} Deck", deck_questions_path(@deck) %></li>
        <li class="is-active"><a href="#" aria-current="page">Editing Question</a></li>
      </ul>
    </nav>
    <%= link_to 'Cancel', deck_questions_path(@deck), class: "level-right ml-2 #{button_classes('is-primary')}" %>
  </header>
</section>

<%= render 'form', deck: @deck, question: @question %>

app/views/questions/index.html.erb
<% content_for(:title, 'Deck Questions') %>

<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><%= link_to 'Decks', decks_path %></li>
    <li class="is-active"><a href="#" aria-current="page"><%= @deck.name %></a></li>
  </ul>
</nav>

<header class='level'>
  <h1 class='title is-1 level-left'><%= @deck.name %> Questions</h1>
  <%= link_to '+ New Question', new_deck_question_path(@deck), class: "level-right #{button_classes}" %>
</header>

<%= render partial: 'shared/search_form', locals: { destination_url: deck_questions_path(deck: @deck) } %>

<table class='<%= table_classes %>'>
  <thead>
    <tr>
      <th></th>
      <th>Adult Content</th>
      <th colspan='1'>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td><%= boolean_checkmark(question.adult_rating?) %></td>
        <td><%= link_to 'Edit', edit_deck_question_path(deck: @deck, id: question) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @questions, :page_links => false %>

app/views/questions/new.html.erb
<% content_for(:title, "New Question") %>

<section class='section'>
  <header class='level'>
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><%= link_to 'Decks', decks_path %></li>
        <li><%= link_to "#{@deck.name} Deck", deck_questions_path(@deck) %></li>
        <li class="is-active"><a href="#" aria-current="page">New Question</a></li>
      </ul>
    </nav>
    <%= link_to 'Cancel', deck_questions_path(@deck), class: "level-right ml-2 #{button_classes('is-primary')}" %>
  </header>
</section>

<%= render 'form', deck: @deck, question: @question %>

app/views/questions/new_from_suggestion.html.erb
<section class='section'>
  <%= form_with(model: @question, local: true) do |form| %>
  <%= render 'shared/errors', object: @question %>

  <%= hidden_field_tag(:suggested_question_id, @suggested_question.id) %>

  <div class='columns'>
    <div class='field column is-half'>
      <div class='control'>
        <%= form.label 'Question' %>
        <%= form.text_field :text, class: 'input' %>
      </div>
    </div>

    <div class='field column is-one-quarter'>
      <div class='control'>
        <%= form.label 'Deck' %><br>
        <div class='select'>
          <%= form.collection_select :deck_id, current_user.decks, :id, :name, {}, class: 'select' %>
        </div>
      </div>
    </div>

    <div class='field column is-one-quarter'>
      <div class='control'>
        <label class='checkbox'>
          <%= form.check_box :adult_rating, class: 'checkbox' %>
          Adult Rating
        </label>
      </div>
    </div>
  </div><!-- columns -->

  <div class='mt-5 mb-5'>
    <%= form.submit 'Submit', class: button_classes %>
  </div>
  <% end %>
</section>