config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'players#new'

  mount ActionCable.server => '/cable'

  # Skip registrations for now so no new users can sign up.
  devise_for :users, skip: [:registrations]

  # Allow users to sign up and automatically populate categories and post types
  # devise_for :users, controllers: { registrations: 'registrations' }

  post 'play', to: 'games#players_ready', as: 'players_ready'
  get 'play', to: 'players#new', as: 'join_game'
  get 'play/:game_code', to: 'players#new_with_code', as: 'join_game_with_code'

  resources :players, only: [:new, :create]
  resources :games, only: [:index, :new, :create, :show, :update] do
    get 'in_progress', to: 'games#game_in_progress', as: 'in_progress'
    resources :players, only: [:index]
    resources :rounds, only: [:show] do
      resources :submissions, only: [:new, :create]
    end
  end

  resources :decks, only: [:index, :new, :create, :edit, :update] do
    resources :questions, only: [:index, :new, :create, :edit, :update]
  end
  resources :questions, only: [:create]
  get '/convert_from_suggestion', to: 'questions#convert_from_suggestion'
  resources :suggested_questions, only: [:new, :create, :index, :show]
end

app/models/game.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: games
#
#  id                      :bigint           not null, primary key
#  adult_content_permitted :boolean          default(FALSE)
#  code                    :string
#  max_rounds              :integer
#  players_ready           :boolean          default(FALSE)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  user_id                 :bigint           not null
#
# Indexes
#
#  index_games_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Game < ApplicationRecord
  DEFAULT_MAX_ROUNDS = 10

  belongs_to :user
  has_many :players, inverse_of: :game, dependent: :destroy
  has_many :rounds, dependent: :destroy
  has_many :game_decks, dependent: :destroy
  has_many :decks, through: :game_decks
  accepts_nested_attributes_for :players,
                                allow_destroy: true, # allows user to delete player via checkbox
                                reject_if: :all_blank # at least 1 player should be present
  before_create :generate_code

  validates :max_rounds,
            presence: true,
            numericality: { greater_than: 0 }

  def self.current
    where('created_at >= ?', 1.hour.ago)
  end

  def self.current_codes
    current.pluck(:code)
  end

  def self.past
    where('created_at < ?', 1.hour.ago)
  end

  def expired?
    if complete?
      rounds.last.submissions.last.created_at < 30.minutes.ago
    else
      created_over_2_hours_ago?
    end
  end

  def active?
    players_ready? && !expired?
  end

  def date
    created_at.strftime('%m-%d-%Y')
  end

  def generate_rounds
    available_questions = generate_questions
    rounds_count = available_questions.length < max_rounds ? available_questions.length : max_rounds
    round_numbers = (1..rounds_count).to_a

    available_questions.each do |question|
      rounds.create!(
        number: round_numbers.shift,
        question_id: question.id
      )
    end
  end

  def complete?
    complete_status = rounds.map(&:complete?).uniq
    complete_status.size == 1 && complete_status.first == true
  end

  def winner
    return unless complete?

    vote_results = votes_by_candidate
    return nil if no_rounds_have_a_winner?(vote_results)

    winning_player_id = vote_results.first[0]
    @winner ||= players.find(winning_player_id)
  end

  def tied?
    winner.blank?
  end

  def created_over_2_hours_ago?
    created_at <= 2.hours.ago
  end

  def submissions
    round_ids = rounds.pluck(:id)
    Submission.where(round_id: round_ids)
  end

  def total_rounds
    # max_rounds becomes inaccurate if it has been overridden
    # by a smaller number of available_questions.
    # this only works if game is in-play.
    rounds.length
  end

  private

  def generate_code
    acceptable_letters = ('A'..'Z').to_a - %w[O I]
    letters = acceptable_letters.shuffle
    self.code = ''
    4.times { self.code += letters.sample }
  end

  def generate_questions
    base_questions = ::Question.active.where(deck_id: deck_ids)

    if adult_content_permitted?
      base_questions.sample(max_rounds)
    else
      base_questions.without_adult_content.sample(max_rounds)
    end
  end

  def no_rounds_have_a_winner?(vote_results)
    return true if (vote_results == []) || there_is_a_tie?(vote_results)
  end

  def there_is_a_tie?(vote_results)
    return false if vote_results.size == 1

    vote_results.first[1] == vote_results.second[1]
  end

  def votes_by_candidate
    results = {}
    rounds_with_winners.each do |round|
      if results[round.winner.id].present?
        results[round.winner.id] += 1
      else
        results[round.winner.id] = 1
      end
    end

    results.sort_by { |_candidate, votes| -votes }
  end

  def rounds_with_winners
    rounds.select { |round| round.winner.present? }.compact
  end
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE)
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy
  has_many :decks, dependent: :destroy
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create update]
  before_action :set_game, only: %i[show update players_ready]
  before_action :redirect_to_play, only: %i[show]

  def index
    @current_games = current_user.games
                                 .current
                                 .order('created_at DESC')
    @past_games = current_user.games
                              .past
                              .order('created_at DESC')
                              .paginate(page: params[:page], per_page: 30)
  end

  def new
    @game = current_user.games.new(
      max_rounds: Game::DEFAULT_MAX_ROUNDS,
      deck_ids: Deck.default_decks.pluck(:id)
    )
    5.times { @game.players.build }
  end

  def show
    authorize(@game)

    # Trying to get all browsers to go to the game#show when a single
    # player clicks the button. Causes infinite loop.
    # RoundChannel.broadcast_to @game.rounds.last,
    #                          game_code: @game.code,
    #                          game_over: true,
    #                          destination_url: game_url(@game)
    delete_cookies
  end

  def create
    @game = current_user.games.new(game_params)

    if @game.save
      @game.generate_rounds
      notice = "Oh SNAP! It's about to be <em>on</em>. Game #{@game.code} is ready to rock!"
      redirect_to games_url, notice: notice
    else
      render :new
    end
  end

  def update
    authorize(@game)

    if @game.update(game_params)
      redirect_to games_url
    else
      render :edit
    end
  end

  def players_ready
    @game.update(players_ready: true)
    GameChannel.broadcast_to @game,
                             game_code: @game.code,
                             player_name: 'undefined',
                             game_activated: @game.active?,
                             destination_url: new_game_round_submission_url(@game, @game.rounds.first)

    redirect_to new_game_round_submission_url(@game, @game.rounds.first)
  end

  def game_in_progress
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def redirect_to_play
    set_game
    redirect_to join_game_path if @game.expired? && @game.complete? && current_user.blank?
  end

  def game_params
    params.require(:game).permit(:user_id,
                                 :adult_content_permitted,
                                 :max_rounds,
                                 :players_ready,
                                 players_attributes: %i[id name _destroy],
                                 deck_ids: [])
  end

  def delete_cookies
    cookie_names = %i[player_id game_id]
    cookie_names.each do |name|
      cookies.delete(name)
    end
  end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
  # rubocop:disable Rails/OutputSafety

  def display_player_names(game)
    players = game.players
    return nil if players.blank?

    winner = game.winner
    output = "#{winner_intro(winner)}, "
    everyone_else = players - [winner]
    output += everyone_else.map(&:name).join(', ')
    output.html_safe
  end

  def display_deck_names(game)
    game.decks.map(&:name).join(', ')
  end

  def display_player_names_and_points(game)
    players = game.players
    return link_to 'Add Players', edit_game_path(game) if players.blank?

    everyone_else = players - [game.winner]
    output = ''
    output += everyone_else.map do |player|
      "#{player.name}: #{pluralize(player.rounds_won, 'round')}"
    end.join(' | ')
    output.html_safe
  end

  def rounds_won_as_emojis(player)
    emojis = ''
    player.rounds_won.times do |_win|
      emojis += '⭐ '
    end
    emojis
  end

  def overall_votes_as_emojis(player)
    emojis = ''
    player.votes.times do |_vote|
      emojis += '✅ '
    end
    emojis
  end

  def winner_icon
    "<i class='fas fa-crown'></i>"
  end

  def tie_icon
    '<i class="far fa-handshake"></i>'
  end

  def share_link(game)
    "#{root_url}play/#{game.code}"
  end

  def form_decks(user)
    return (Deck.default_decks + user.decks.order(:name)) unless user.admin?

    user.decks.order(:name)
  end

  private

  def winner_intro(winner)
    winner ? "#{winner_icon} <strong>#{winner.name}</strong>" : "#{tie_icon} Tied"
  end

  # rubocop:enable Rails/OutputSafety
end

app/views/games/game_in_progress.html.erb
<section class='section centered'>
  <h1 class='title is-h1'>😕</h1>
  <h1 class='title branded centered'>Sorry!<br>This game is no longer accepting players.</h1>
  <p>You'll have to wait for another game to start.</p>

  <%= link_to ('<i class="fas fa-gamepad mr-2"></i>'.html_safe + 'Join Another Game'), join_game_path, class: "#{button_classes} mt-5" %><br>
</section>

app/views/games/index.html.erb
<% content_for(:title, "Games") %>

<section class='section'>
  <div class='level'>
    <div class='level-left'></div>
    <div class='level-right'>
      <%= link_to '+ New Game', new_game_path, class: "level-item mb-3 #{button_classes}" %>
    </div>
  </div>
</section>

<section class='section'>
  <% if @current_games.any? %>
  <h2 class='title is-2'>Current Games</h2>

  <% @current_games.each do |game| %>
  <div class="tile is-ancestor">
    <div class="tile is-12">
      <div class="tile is-parent">
        <article class="tile is-child notification is-light">
          <p class="title"><%= game.code %>: <%= game.date %></p>
          <div class="content">
            <p>Share Link: <%= link_to share_link(game), share_link(game) %></p>
            <p>
              Adult Content? <%= boolean_check_or_x(game.adult_content_permitted?) %> |
              Players Ready? <%= boolean_check_or_x(game.players_ready?) %> |
              Game Over? <%= boolean_check_or_x(game.complete?) %>
            </p>
            <p>Players: <%= display_player_names(game) if game.players.any? %></p>
            <p>Decks: <%= display_deck_names(game) %></p>
            <p>Questions:</p>
            <ol>
              <% game.rounds.each do |round| %>
              <li>
                <%= round.question.text %>
                <% if round.winner.present? %>
                | <%= link_to 'see results', game_round_path(game, round) %>
                <% end %>
              </li>
              <% end %>
            </ol>
          </div>
        </article>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
</section>

<section class='section'>
  <h2 class='title is-2'>Past Games</h2>
  <table class="<%= table_classes %>">
    <thead>
      <tr>
        <th>Date Played</th>
        <th>Game Code</th>
        <th>Decks Used</th>
        <th>Players</th>
        <th>Players Ready?</th>
        <th>Game Complete?</th>
      </tr>
    </thead>
    <tbody>
      <% @past_games.each do |game| %>
      <tr>
        <td><%= game.date %></td>
        <td><%= link_to game.code, game %></td>
        <td><%= display_deck_names(game) %></td>
        <td><%= display_player_names(game) %></td>
        <td><%= boolean_check_or_x(game.players_ready?) %></td>
        <td><%= boolean_check_or_x(game.complete?) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</section>

<section class='section'>
  <%= will_paginate @past_games, :page_links => false %>
</section>

app/views/games/new.html.erb
<% content_for(:title, 'New Game') %>

<section class='section'>
  <header class='level'>
    <h1 class='title is-1 level-left'>New Game</h1>
    <%= link_to 'Cancel', games_path, class: "level-right #{button_classes('is-primary')}" %>
  </header>
</section>

<section class='section form-narrow'>
  <%= form_with(model: @game, local: true) do |form| %>
    <%= render 'shared/errors', object: @game %>

    <div class='field'>
      <%= form.label 'How Many Rounds Do You Want to Play?' %>
      <%= form.number_field :max_rounds, min: 1, class: 'input' %>
    </div>

    <div class='field'>
      <div class='control'>
        <label class='checkbox'>
          <%= form.check_box :adult_content_permitted, class: 'checkbox' %>
          Allow Adult Content?
        </label>
      </div>
    </div>

    <div class="field">
      <%= form.label 'What Decks Do You Want to Use?' %>
      <%= form.collection_check_boxes :deck_ids, form_decks(current_user), :id, :name do |r| %>
        <div class='form-check'>
          <%= r.check_box class: 'form-check-input' %>
          <%= r.label class: 'form-check-label' %>
        </div>
      <% end %>
    </div>

    <div class="mt-5 mb-5">
      <%= form.submit class: button_classes %>
    </div>
  <% end %>
</section>

app/views/games/show.html.erb
<% content_for(:title, "Game #{@game.code}") %>

<% unless @game.tied? %>
  <marquee>
    ✨<strong>Congrats to <%= display_winner(@game) %> for taking the win!</strong> ✨
    Here's how everyone else ranked... <%= display_player_names_and_points(@game) %>
  </marquee>
<% end %>
<section class="hero mb-5">
  <center>
    <div class="hero-body vertical-center-parent">
      <div class="container grand-winner-box">
        <h2 class="subtitle branded">
          <% unless @game.tied? %>
            Winning <%= @game.winner.rounds_won %> out of <%= pluralize(@game.rounds.length, 'round') %>,<br>
          <% end %>
          the "winner" is...
        </h2>
        <h1 class="winner branded mt-2 mb-5">
            👑💩 <%= display_winner(@game) %>! 🎊🎉
        </h1>

        <% unless @game.tied? %>
          <h2 class="subtitle branded">
            😏 Good job, <%= display_winner(@game) %>. You're a real winner. 😂
          </h2>
        <% end %>
      </div>
    </div>
  </center>
</section>

<section>
  <div class='columns'>
    <div class='column'>
      <section class='section'>
        <h2 class='title is-3 branded'>Rounds Won</h2>
        <table>
          <tbody>
            <% @game.players.each do |player| %>
            <tr>
              <td style='padding-right: 15px;'><span class='title is-5 branded'><%= player.name %></span></td>
              <td><%= rounds_won_as_emojis(player) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </section>

      <section class='section'>
        <h2 class='title is-3 branded'>Total Votes Across All Questions</h2>
        <table>
          <tbody>
            <% @game.players.each do |player| %>
            <tr>
              <td style='padding-right: 15px;'><span class='title is-5 branded'><%= player.name %></span></td>
              <td><%= overall_votes_as_emojis(player) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </section>
    </div>

    <div class='column'>
      <section class='section'>
        <h2 class='title is-3 branded'>Questions</h2>
        <% @game.rounds.each do |round| %>
        <p><%= round.number %>. <%= round.question.text %> → <span class='branded'><%= display_winner(round) %></span></p>
        <% end %>
      </section>
    </div>
  </div>
</section>


<section>
  <%= link_to ('<i class="fas fa-gamepad mr-2"></i>'.html_safe + 'Play Another Game'), join_game_path, class: "#{button_classes} mt-5" %><br>
  <%= link_to '+ Start a New Game', new_game_path, class: "#{button_classes('is-link')} mt-5" if current_user.present? %>
</section>