config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'players#new'

  mount ActionCable.server => '/cable'

  # Skip registrations for now so no new users can sign up.
  devise_for :users, skip: [:registrations]

  # Allow users to sign up and automatically populate categories and post types
  # devise_for :users, controllers: { registrations: 'registrations' }

  post 'play', to: 'games#players_ready', as: 'players_ready'
  get 'play', to: 'players#new', as: 'join_game'
  get 'play/:game_code', to: 'players#new_with_code', as: 'join_game_with_code'

  resources :players, only: [:new, :create]
  resources :games, only: [:index, :new, :create, :show, :update] do
    get 'in_progress', to: 'games#game_in_progress', as: 'in_progress'
    resources :players, only: [:index]
    resources :rounds, only: [:show] do
      resources :submissions, only: [:new, :create]
    end
  end

  resources :decks, only: [:index, :new, :create, :edit, :update] do
    resources :questions, only: [:index, :new, :create, :edit, :update]
  end
  resources :questions, only: [:create]
  get '/convert_from_suggestion', to: 'questions#convert_from_suggestion'
  resources :suggested_questions, only: [:new, :create, :index, :show]
end

app/views/shared/navbar/_main.html.erb
<nav class="navbar is-info mb-5" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= image_tag '/images/nelson.png', class: 'brand-image' %>
    <%= link_to 'BlameGame', root_url, class: 'ml-2 mr-2 nav-brand-name' %>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Play', join_game_path, class: 'navbar-item' %>
      <%= link_to 'Suggest a Question', new_suggested_question_path, class: 'navbar-item' %>
      <%= render 'shared/navbar/signed_in' if current_user.present? %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= session_links %>
        </div>
      </div>
    </div>
  </div>
</nav>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', () => {

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( el => {
      el.addEventListener('click', () => {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>

app/views/shared/navbar/_signed_in.html.erb
<% if current_user.present? %>
  <%= link_to '+ New Game', new_game_path, class: 'navbar-item' %>
  <%= link_to 'Games', games_path, class: 'navbar-item' %>
  <%= link_to 'Custom Decks', decks_path, class: 'navbar-item' %>
  <%= link_to 'Manage Suggested Questions', suggested_questions_path, class: 'navbar-item' if current_user.admin? %>
<% end %>