config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'players#new'

  mount ActionCable.server => '/cable'

  # Skip registrations for now so no new users can sign up.
  devise_for :users, skip: [:registrations]

  # Allow users to sign up and automatically populate categories and post types
  # devise_for :users, controllers: { registrations: 'registrations' }

  post 'play', to: 'games#players_ready', as: 'players_ready'
  get 'play', to: 'players#new', as: 'join_game'
  get 'play/:game_code', to: 'players#new_with_code', as: 'join_game_with_code'

  resources :players, only: [:new, :create]
  resources :games, only: [:index, :new, :create, :show, :update] do
    get 'in_progress', to: 'games#game_in_progress', as: 'in_progress'
    resources :players, only: [:index]
    resources :rounds, only: [:show] do
      resources :submissions, only: [:new, :create]
    end
  end

  resources :decks, only: [:index, :new, :create, :edit, :update] do
    resources :questions, only: [:index, :new, :create, :edit, :update]
  end
  resources :questions, only: [:create]
  get '/convert_from_suggestion', to: 'questions#convert_from_suggestion'
  resources :suggested_questions, only: [:new, :create, :index, :show]
end

app/models/deck.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: decks
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_decks_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Deck < ApplicationRecord
  belongs_to :user
  has_many :questions, dependent: :nullify
  has_many :game_decks, dependent: :destroy
  has_many :games, through: :game_decks

  validates :name, presence: true

  DEFAULT_DECK_NAMES = [
    'Official 1',
    'Official 2',
  ].freeze

  def self.default_decks
    where(name: DEFAULT_DECK_NAMES).order(:name)
  end

  def default?
    DEFAULT_DECK_NAMES.include?(name)
  end
end

app/controllers/decks_controller.rb
# frozen_string_literal: true

class DecksController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create edit update]
  before_action :set_deck, only: %i[edit update]

  def index
    @decks = current_user.decks.all
  end

  def new
    @deck = current_user.decks.new
  end

  def edit
    authorize(@deck)
  end

  def create
    @deck = current_user.decks.new(deck_params)
    authorize(@deck)

    if @deck.save
      redirect_to deck_questions_url(@deck), notice: "#{@deck.name} Deck was created."
    else
      render :new
    end
  end

  def update
    authorize(@deck)
    if @deck.update(deck_params)
      redirect_to decks_url, notice: "#{@deck.name} Deck was updated."
    else
      render :edit
    end
  end

  private

  def set_deck
    @deck = Deck.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name, :user_id)
  end
end

app/views/decks/_form.html.erb
<section class='section'>
  <%= form_with(model: deck, local: true) do |form| %>
    <%= render 'shared/errors', object: deck %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'input' %>
    </div>

    <div class="actions">
      <%= form.submit class: button_classes %>
    </div>
  <% end %>
</section>

app/views/decks/edit.html.erb
<% content_for(:title, "Editing #{@deck.name}") %>

<section class='section'>
  <header class='level'>
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><%= link_to 'Decks', decks_path %></li>
        <li class="is-active"><a href="#" aria-current="page">Editing <%= @deck.name %> Deck</a></li>
      </ul>
    </nav>
    <%= link_to 'Cancel', decks_path, class: "level-right ml-2 #{button_classes('is-primary')}" %>
  </header>
</section>

<%= render 'form', deck: @deck %>

app/views/decks/index.html.erb
<% content_for(:title, 'Decks') %>

<header class='level'>
  <div>
    <h1 class='title is-1 level-left'>Custom Decks</h1>
    <p>You automatically have access to the default BlameGame decks. You can create additional custom decks and questions here.</p>
  </div>
  <%= link_to '+ New Deck', new_deck_path, class: "level-right #{button_classes}" %>
</header>


<section class='section form-narrow'>
  <% @decks.order(:name).each do |deck| %>
    <div class="card mb-5">
      <div class="card-content">
        <p class="title">
          <%= link_to "#{deck.name} Deck", deck_questions_path(deck) %>
        </p>
        <p class="subtitle">
          Questions: <%= deck.questions.active.length %>
        </p>
      </div>
      <footer class="card-footer">
        <p class="card-footer-item">
          <span>
            <%= link_to 'Edit Deck', edit_deck_path(deck) %>
          </span>
        </p>
        <p class="card-footer-item">
          <span>
            <%= link_to 'Questions', deck_questions_path(deck) %>
          </span>
        </p>
      </footer>
    </div>
  <% end %>

</section>

app/views/decks/new.html.erb
<section class='section'>
  <header class='level'>
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><%= link_to 'Decks', decks_path %></li>
        <li class="is-active"><a href="#" aria-current="page">New Deck</a></li>
      </ul>
    </nav>
    <%= link_to 'Cancel', decks_path, class: "level-right ml-2 #{button_classes('is-primary')}" %>
  </header>
</section>
<%= render 'form', deck: @deck %>